version: '2'
services:
    php-apache-dev:
        image: webdevops/php-apache-dev
        ports:
            - '82:80'
        links:
            - 'mariadb:db'
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - './:/app'
    mariadb:
        image: mariadb
        ports:
            - '3362:3306'
        volumes:
            - './mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=demo1234
            - DATABASE=demo
