version: '2'
services:
    php-apache-dev:
        image: webdevops/php-apache-dev
        ports:
            - '82:80'
        links:
            - 'mariadb:db'
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - './:/app'
