version: '2'
services:
    php-apache-dev:
        image: webdevops/php-apache-dev:7.4-alpine
        ports:
            - '82:80'
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - './:/app'
