version: '2'
services:
    php-apache-dev:
        build: .
        ports:
            - '82:80'
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        volumes:
            - './:/app'
